/*
The data was downloaded from https://www.who.int/tools/child-growth-standards/standards
and excel was used to convert the kilograms to pouns by multiplying by 2.204623
1 kg = 2.204623 lb
x: month
y: weight in pounds

*/

export var GIRLS_WEIGHT_FOR_AGE_BIRTH_TO_TWO_YEARS_US_CUSTOMARY_SYSTEM = [
  {
    name: "3rd",
    series: [
      { name: "0", value: "1.1" },
      { name: "1", value: "1.5" },
      { name: "2", value: "1.8" },
      { name: "3", value: "2.1" },
      { name: "4", value: "2.3" },
      { name: "5", value: "2.5" },
      { name: "6", value: "2.6" },
      { name: "7", value: "2.8" },
      { name: "8", value: "2.9" },
      { name: "9", value: "3" },
      { name: "10", value: "3.1" },
      { name: "11", value: "3.2" },
      { name: "12", value: "3.2" },
      { name: "13", value: "3.3" },
      { name: "14", value: "3.4" },
      { name: "15", value: "3.5" },
      { name: "16", value: "3.5" },
      { name: "17", value: "3.6" },
      { name: "18", value: "3.7" },
      { name: "19", value: "3.8" },
      { name: "20", value: "3.9" },
      { name: "21", value: "3.9" },
      { name: "22", value: "4" },
      { name: "23", value: "4.1" },
      { name: "24", value: "4.2" },
    ],
  },
  {
    name: "5th",
    series: [
      { name: "0", value: "1.1" },
      { name: "1", value: "1.5" },
      { name: "2", value: "1.9" },
      { name: "3", value: "2.1" },
      { name: "4", value: "2.4" },
      { name: "5", value: "2.5" },
      { name: "6", value: "2.7" },
      { name: "7", value: "2.9" },
      { name: "8", value: "2.9" },
      { name: "9", value: "3.1" },
      { name: "10", value: "3.2" },
      { name: "11", value: "3.3" },
      { name: "12", value: "3.3" },
      { name: "13", value: "3.4" },
      { name: "14", value: "3.5" },
      { name: "15", value: "3.6" },
      { name: "16", value: "3.7" },
      { name: "17", value: "3.7" },
      { name: "18", value: "3.8" },
      { name: "19", value: "3.9" },
      { name: "20", value: "3.9" },
      { name: "21", value: "4" },
      { name: "22", value: "4.1" },
      { name: "23", value: "4.2" },
      { name: "24", value: "4.3" },
    ],
  },
  {
    name: "10th",
    series: [
      { name: "0", value: "1.2" },
      { name: "1", value: "1.6" },
      { name: "2", value: "2" },
      { name: "3", value: "2.3" },
      { name: "4", value: "2.5" },
      { name: "5", value: "2.7" },
      { name: "6", value: "2.8" },
      { name: "7", value: "2.9" },
      { name: "8", value: "3.1" },
      { name: "9", value: "3.2" },
      { name: "10", value: "3.3" },
      { name: "11", value: "3.4" },
      { name: "12", value: "3.5" },
      { name: "13", value: "3.6" },
      { name: "14", value: "3.6" },
      { name: "15", value: "3.7" },
      { name: "16", value: "3.8" },
      { name: "17", value: "3.9" },
      { name: "18", value: "4" },
      { name: "19", value: "4" },
      { name: "20", value: "4.1" },
      { name: "21", value: "4.2" },
      { name: "22", value: "4.3" },
      { name: "23", value: "4.4" },
      { name: "24", value: "4.4" },
    ],
  },
  {
    name: "15th",
    series: [
      { name: "0", value: "1.3" },
      { name: "1", value: "1.6" },
      { name: "2", value: "2" },
      { name: "3", value: "2.3" },
      { name: "4", value: "2.5" },
      { name: "5", value: "2.8" },
      { name: "6", value: "2.9" },
      { name: "7", value: "3" },
      { name: "8", value: "3.2" },
      { name: "9", value: "3.3" },
      { name: "10", value: "3.4" },
      { name: "11", value: "3.5" },
      { name: "12", value: "3.6" },
      { name: "13", value: "3.7" },
      { name: "14", value: "3.8" },
      { name: "15", value: "3.9" },
      { name: "16", value: "3.9" },
      { name: "17", value: "4" },
      { name: "18", value: "4.1" },
      { name: "19", value: "4.2" },
      { name: "20", value: "4.3" },
      { name: "21", value: "4.4" },
      { name: "22", value: "4.4" },
      { name: "23", value: "4.5" },
      { name: "24", value: "4.6" },
    ],
  },
  {
    name: "25th",
    series: [
      { name: "0", value: "1.3" },
      { name: "1", value: "1.7" },
      { name: "2", value: "2.1" },
      { name: "3", value: "2.4" },
      { name: "4", value: "2.7" },
      { name: "5", value: "2.9" },
      { name: "6", value: "3" },
      { name: "7", value: "3.2" },
      { name: "8", value: "3.3" },
      { name: "9", value: "3.4" },
      { name: "10", value: "3.5" },
      { name: "11", value: "3.6" },
      { name: "12", value: "3.7" },
      { name: "13", value: "3.8" },
      { name: "14", value: "3.9" },
      { name: "15", value: "4" },
      { name: "16", value: "4.1" },
      { name: "17", value: "4.2" },
      { name: "18", value: "4.3" },
      { name: "19", value: "4.4" },
      { name: "20", value: "4.4" },
      { name: "21", value: "4.5" },
      { name: "22", value: "4.6" },
      { name: "23", value: "4.7" },
      { name: "24", value: "4.8" },
    ],
  },
  {
    name: "50th",
    series: [
      { name: "0", value: "1.5" },
      { name: "1", value: "1.9" },
      { name: "2", value: "2.3" },
      { name: "3", value: "2.6" },
      { name: "4", value: "2.9" },
      { name: "5", value: "3.1" },
      { name: "6", value: "3.3" },
      { name: "7", value: "3.4" },
      { name: "8", value: "3.6" },
      { name: "9", value: "3.7" },
      { name: "10", value: "3.9" },
      { name: "11", value: "3.9" },
      { name: "12", value: "4" },
      { name: "13", value: "4.2" },
      { name: "14", value: "4.3" },
      { name: "15", value: "4.4" },
      { name: "16", value: "4.4" },
      { name: "17", value: "4.5" },
      { name: "18", value: "4.6" },
      { name: "19", value: "4.7" },
      { name: "20", value: "4.8" },
      { name: "21", value: "4.9" },
      { name: "22", value: "5" },
      { name: "23", value: "5.1" },
      { name: "24", value: "5.2" },
    ],
  },
  {
    name: "75th",
    series: [
      { name: "0", value: "1.6" },
      { name: "1", value: "2.1" },
      { name: "2", value: "2.5" },
      { name: "3", value: "2.9" },
      { name: "4", value: "3.2" },
      { name: "5", value: "3.4" },
      { name: "6", value: "3.6" },
      { name: "7", value: "3.8" },
      { name: "8", value: "3.9" },
      { name: "9", value: "4" },
      { name: "10", value: "4.2" },
      { name: "11", value: "4.3" },
      { name: "12", value: "4.4" },
      { name: "13", value: "4.5" },
      { name: "14", value: "4.6" },
      { name: "15", value: "4.7" },
      { name: "16", value: "4.9" },
      { name: "17", value: "4.9" },
      { name: "18", value: "5" },
      { name: "19", value: "5.2" },
      { name: "20", value: "5.3" },
      { name: "21", value: "5.4" },
      { name: "22", value: "5.4" },
      { name: "23", value: "5.6" },
      { name: "24", value: "5.7" },
    ],
  },
  {
    name: "85th",
    series: [
      { name: "0", value: "1.7" },
      { name: "1", value: "2.2" },
      { name: "2", value: "2.7" },
      { name: "3", value: "3" },
      { name: "4", value: "3.3" },
      { name: "5", value: "3.5" },
      { name: "6", value: "3.8" },
      { name: "7", value: "3.9" },
      { name: "8", value: "4.1" },
      { name: "9", value: "4.2" },
      { name: "10", value: "4.4" },
      { name: "11", value: "4.5" },
      { name: "12", value: "4.6" },
      { name: "13", value: "4.7" },
      { name: "14", value: "4.9" },
      { name: "15", value: "4.9" },
      { name: "16", value: "5.1" },
      { name: "17", value: "5.2" },
      { name: "18", value: "5.3" },
      { name: "19", value: "5.4" },
      { name: "20", value: "5.5" },
      { name: "21", value: "5.6" },
      { name: "22", value: "5.7" },
      { name: "23", value: "5.8" },
      { name: "24", value: "5.9" },
    ],
  },
  {
    name: "90th",
    series: [
      { name: "0", value: "1.8" },
      { name: "1", value: "2.3" },
      { name: "2", value: "2.7" },
      { name: "3", value: "3.1" },
      { name: "4", value: "3.4" },
      { name: "5", value: "3.7" },
      { name: "6", value: "3.9" },
      { name: "7", value: "4" },
      { name: "8", value: "4.2" },
      { name: "9", value: "4.4" },
      { name: "10", value: "4.5" },
      { name: "11", value: "4.6" },
      { name: "12", value: "4.8" },
      { name: "13", value: "4.9" },
      { name: "14", value: "5" },
      { name: "15", value: "5.1" },
      { name: "16", value: "5.2" },
      { name: "17", value: "5.4" },
      { name: "18", value: "5.4" },
      { name: "19", value: "5.6" },
      { name: "20", value: "5.7" },
      { name: "21", value: "5.8" },
      { name: "22", value: "5.9" },
      { name: "23", value: "6" },
      { name: "24", value: "6.1" },
    ],
  },
  {
    name: "95",
    series: [
      { name: "0", value: "1.8" },
      { name: "1", value: "2.4" },
      { name: "2", value: "2.9" },
      { name: "3", value: "3.3" },
      { name: "4", value: "3.6" },
      { name: "5", value: "3.8" },
      { name: "6", value: "4" },
      { name: "7", value: "4.3" },
      { name: "8", value: "4.4" },
      { name: "9", value: "4.6" },
      { name: "10", value: "4.7" },
      { name: "11", value: "4.9" },
      { name: "12", value: "5" },
      { name: "13", value: "5.1" },
      { name: "14", value: "5.2" },
      { name: "15", value: "5.4" },
      { name: "16", value: "5.5" },
      { name: "17", value: "5.6" },
      { name: "18", value: "5.7" },
      { name: "19", value: "5.9" },
      { name: "20", value: "5.9" },
      { name: "21", value: "6.1" },
      { name: "22", value: "6.2" },
      { name: "23", value: "6.3" },
      { name: "24", value: "6.4" },
    ],
  },
  {
    name: "97th",
    series: [
      { name: "0", value: "1.9" },
      { name: "1", value: "2.4" },
      { name: "2", value: "2.9" },
      { name: "3", value: "3.4" },
      { name: "4", value: "3.7" },
      { name: "5", value: "3.9" },
      { name: "6", value: "4.2" },
      { name: "7", value: "4.4" },
      { name: "8", value: "4.5" },
      { name: "9", value: "4.7" },
      { name: "10", value: "4.9" },
      { name: "11", value: "5" },
      { name: "12", value: "5.1" },
      { name: "13", value: "5.3" },
      { name: "14", value: "5.4" },
      { name: "15", value: "5.5" },
      { name: "16", value: "5.7" },
      { name: "17", value: "5.8" },
      { name: "18", value: "5.9" },
      { name: "19", value: "6" },
      { name: "20", value: "6.1" },
      { name: "21", value: "6.3" },
      { name: "22", value: "6.4" },
      { name: "23", value: "6.5" },
      { name: "24", value: "6.6" },
    ],
  },
];
